# Generated by Django 6.0.2 on 2026-02-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name as captured during lead intake.", max_length=255)),
                ('phone', models.CharField(help_text='Primary contact number used by operations teams for coordination.', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Optional email address for communication and notifications.', max_length=254, null=True)),
                ('address', models.TextField(help_text='Service address in free-text form as provided by the customer.')),
                ('cycle_brand', models.CharField(blank=True, help_text="Optional brand of the customer's cycle, if known.", max_length=255, null=True)),
                ('cycle_model', models.CharField(blank=True, help_text="Optional model of the customer's cycle, if known.", max_length=255, null=True)),
                ('city', models.ForeignKey(help_text='City in which this customer resides or where service is requested.', on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='cities.city')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
