# Generated by Django 6.0.2 on 2026-02-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name or identifier used by operations to refer to the technician.', max_length=255)),
                ('technician_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('AGENCY', 'Agency')], default='INTERNAL', help_text='Indicates whether the technician is an internal resource or an agency resource.', max_length=20)),
                ('base_location', models.TextField(help_text="Free-text description of the technician's usual starting point (e.g., neighborhood, depot address) to support routing decisions later.")),
                ('is_available', models.BooleanField(default=True, help_text='Indicates whether this technician is currently available for scheduling without deactivating them or removing historical data.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive technicians are excluded from future scheduling.')),
                ('daily_capacity', models.PositiveIntegerField(default=4, help_text='Target number of jobs this technician can handle per day.')),
                ('city', models.ForeignKey(help_text='Primary city in which this technician usually operates.', on_delete=django.db.models.deletion.PROTECT, related_name='technicians', to='cities.city')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
