# Generated by Django 6.0.2 on 2026-02-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='base_latitude',
            field=models.FloatField(blank=True, help_text='Base/home latitude; starting origin for route planning.', null=True),
        ),
        migrations.AddField(
            model_name='technician',
            name='base_longitude',
            field=models.FloatField(blank=True, help_text='Base/home longitude; starting origin for route planning.', null=True),
        ),
    ]
