# Generated by Django 6.0.2 on 2026-02-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable name of the city as used by operations teams.', max_length=255, unique=True)),
                ('handling_type', models.CharField(choices=[('DIRECT', 'Direct'), ('AGENCY', 'Agency-only'), ('HYBRID', 'Hybrid')], default='DIRECT', help_text='Determines whether CycleWorks schedules jobs internally, forwards them to an external agency, or splits them in a hybrid model.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive cities are hidden from day-to-day scheduling operations.')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ('name',),
            },
        ),
    ]
