# Generated by Django 6.0.2 on 2026-02-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Calendar date on which this slot occurs.')),
                ('start_time', models.TimeField(help_text='Start time of the 2-hour service window.')),
                ('end_time', models.TimeField(help_text='End time of the 2-hour service window.')),
                ('max_capacity', models.PositiveIntegerField(help_text='Maximum number of bookings that can be planned into this slot.')),
                ('current_utilization', models.PositiveIntegerField(default=0, help_text='Current count of bookings assigned to this slot.')),
                ('city', models.ForeignKey(help_text='City in which this slot is scheduled.', on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='cities.city')),
            ],
            options={
                'ordering': ('date', 'start_time', 'city'),
                'unique_together': {('date', 'start_time', 'end_time', 'city')},
            },
        ),
    ]
