# Generated by Django 6.0.2 on 2026-02-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('customers', '0001_initial'),
        ('slots', '0001_initial'),
        ('technicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(help_text='Target date on which service is planned to occur.')),
                ('handling_decision', models.CharField(blank=True, choices=[('INTERNAL', 'Internal'), ('AGENCY', 'Agency')], help_text='In hybrid cities, indicates whether this particular booking is handled by internal technicians or forwarded to an external agency.', max_length=20, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CONFIRMED', 'Confirmed'), ('RESOLUTION_REQUIRED', 'Resolution required'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled'), ('FORWARDED_TO_AGENCY', 'Forwarded to agency')], default='REQUESTED', help_text='Current state of the booking in the scheduling workflow.', max_length=32)),
                ('notes', models.TextField(blank=True, help_text='Operations notes, customer constraints, or exception details.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the booking was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the most recent update to this booking.')),
                ('city', models.ForeignKey(help_text="Operational city context for this booking. Usually matches the customer's city, but stored explicitly for reporting and routing.", on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cities.city')),
                ('customer', models.ForeignKey(help_text='Customer who requested the service.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer')),
                ('slot', models.ForeignKey(blank=True, help_text='Tentative 2-hour slot for this booking once it enters the planning phase. May be null while still in early stages.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='slots.slot')),
                ('technician', models.ForeignKey(blank=True, help_text='Assigned technician for this booking once scheduling is finalized. May be null before assignment.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='technicians.technician')),
            ],
            options={
                'ordering': ('-service_date', '-created_at'),
                'indexes': [models.Index(fields=['service_date', 'city'], name='bookings_bo_service_195689_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx')],
            },
        ),
    ]
