# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="Service location latitude for routing; geocoded from address.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="Service location longitude for routing; geocoded from address.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="route_position",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Stop order in technician's route (1-based); set by dispatch optimizer.",
                null=True,
            ),
        ),
    ]
